### ISSUE TITLE
App crashes after SSH command 

### ISSUE THREAD

**Issue by F3000** [louisdh/openterm#120]
I typ following command : 
ssh pi@10.0.0.46 -p password 

After that the app crashes ...

**Comment by holzschu** [comment]
I can't reproduce the bug with the latest version of `ios_system`, which probably means it has been solved. Can someone test on OpenTerm 2.0?
"-p password" won't work anyway (this version of ssh only supports key-based authentification) but that is a different issue.

**Comment by louisdh** [comment]
Seems to be fixed in the latest TestFlight beta.
