### ISSUE TITLE
Network commands

### ISSUE THREAD

**Issue by Spydar007** [louisdh/openterm#57]
It'd be great to have network commands such as `ping`, `telnet` and `dig` for native command-line network diagnostics from iOS.

**Comment by louisdh** [comment]
@holzschu What's the status of these commands in [ios_system](https://github.com/holzschu/ios_system)?

**Comment by holzschu** [comment]
ping: done once already, removed, would be easy to add back. 
telnet: I tried, it couldn't compile it (it requires some header file that I couldn't locate), also without interactivity, the interest is limited.
dig: I didn't try. I'll look into it.

**Comment by palmin** [comment]
[netcat](https://en.wikipedia.org/wiki/Netcat) can often be used in some of the same situations as telnet and it is easier to use in a non-interactive way and maybe it is easier to compile as well?

I was afraid it was GPL licensed and it was 🙀, but there is a BSD version as well.

**Comment by holzschu** [comment]
I'm starting to work on `network_ios`: https://github.com/holzschu/network_ios
I've added netcat to the list (ping, dig, netcat).

**Comment by holzschu** [comment]
The good news: netcat (BSD) works. The bad news: I have no way to test it thoroughly, except that: 
- it produces mostly "Operation timed out" on random addresses and ports (as it should). 
- it produces valid information, on say "nc -zv www.google.fr 80" or "nc -zv smtp.[redacted] 25"

**Comment by louisdh** [comment]
The following network commands have been added and will be available in OpenTerm 2.0:
dig, host, nc, nslookup, ping, rlogin, ssh-keygen, telnet
