### ISSUE TITLE
Document and/or file provider compatibility

### ISSUE THREAD

**Issue by nighthawk** [louisdh/openterm#8]
I'm wondering if this app could be made compatible with [document or file providers](https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/FileProvider.html).

It could allow you to use Terminal to search for things using `grep` or reorganise files using the file system commands, that are stored in other apps. That would be awesome to interact with your iCloud Drive, Dropbox or the local checkout of a git repository from [Working Copy](https://workingcopyapp.com/).

Similarly other apps could get access to the data stored in Terminal's sandbox. That would especially be useful for text editors like [Textastic](https://www.textasticapp.com/) or [Pythonista](http://omz-software.com/pythonista/).

Not sure if this is possible or feasible, but something to consider.

**Comment by holzschu** [comment]
The way the iOS Sandbox works (currently), a program can not access the data in another app automatically. There must be a user interaction with the interface. Which is Apple's way to ensure security: you must explicitly grant an application access to a file in another app sandbox, by clicking on it.

So: using the Files app, you can drag a folder from WorkingCopy, operate on it in Terminal (or iVim), drag it back to WorkingCopy, and commit your changes. That is permitted by the system (and WorkingCopy will, cleverly, only commit the files that have been actually changed). You can use iVim to open a file in Terminal sandbox, that is also permitted. 

But you can't start a command in Terminal that operates on a file in the WorkingCopy directory. Believe me, I tried really hard.

**Comment by nighthawk** [comment]
Hmm, I see. Though I'm not sure I fully follow. Say, Pythonista let's me open a *folder* from Working Copy through the file picker UI, but then I can just change whatever I want in that folder right in Pythonista without having to go through the file picker sandbox again. Couldn't it work the same in Terminal or iVim? You have that explicit step first to pick the parent directory, but then everything else in handled in the host app?

(Alas, I just tried to emulate this using [Stash](https://github.com/ywangd/stash), but could only get to Pythonista's local files and none of those stored in iCloud or Working Copy.)

**Comment by holzschu** [comment]
You're absolutely right, opening a folder gives the Pythonista app the rights on the entire sub-hierarchy. I'll have to look into it. First step: find how to open a directory instead of a file.

**Comment by holzschu** [comment]
I have reproduced what Pythonista does in iVim: https://github.com/holzschu/iVim
It would just require adding a document picker to Terminal:
```
let picker = UIDocumentPickerViewController(documentTypes: types, in: mode)
picker.allowsMultipleSelection = true
```

**Comment by nighthawk** [comment]
One gotcha with this according to the developer of Textastic:

> opening a directory is only supported for local directories that are stored on the device (like Working Copy). Apple's current API does not allow to open remote directories in this way.

So it won't be possible for all file providers: Dropbox and FileBrowser (sftp) won't work, but Working Copy should work. iCloud Drive seems to be a mix where only the files cached on the device have their contents accessible...

**Comment by palmin** [comment]
> So it won't be possible for all file providers: Dropbox and FileBrowser (sftp) won't work, but Working Copy should work. iCloud Drive seems to be a mix where only the files cached on the device have their contents accessible...

If the file provider is well-written it should be possible to ensure files are downloaded onto the device, but doing operations in a file-coordinated way. If the files are not already available on device, you might need to wait a while for the file-coordination to come through.

I'm the developer of Working Copy btw.

**Comment by louisdh** [comment]
I've been looking in to this, and I think there's one problem with adding a document provider to OpenTerm: unless I'm missing something, it looks like the FileManager doesn't allow you to call `changeCurrentDirectoryPath` with a path retrieved from a document provider. 😕

**Comment by palmin** [comment]
Are you aware of the security scope stuff?

https://developer.apple.com/documentation/foundation/nsurl/1417051-startaccessingsecurityscopedreso

**Comment by louisdh** [comment]
@palmin Oh wow, I missed that. Got it working now!

**Comment by palmin** [comment]
There are extra steps if the app should be able to remember the directories that it has ever opened, such that it has access next time it runs. URLs needs to be saved and restored in a certain way as bookmarks. 

You can see a example of this here:
https://github.com/palmin/open-in-place/blob/3748f4c26260aa958b322502403961e2d216fecc/OpenInPlace/ListController.swift#L226

**Comment by louisdh** [comment]
@palmin Ok, thank you!

**Comment by IMcD23** [comment]
Check out #65, which adds persisted bookmarks.
